apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: hello-world
        image: registry.cn-hangzhou.aliyuncs.com/tinyedge/hello-world
        imagePullPolicy: IfNotPresent