export const AI1DOC = "http://47.97.253.23:12311/static/doc/sidebar1.html"
export const AI2DOC = "http://47.97.253.23:12311/static/doc/sidebar2.html"
export const AI3DOC = "http://47.97.253.23:12311/static/doc/sidebar3.html"
export const MODEL_DOWNLOAD_URL = "ws://47.98.249.190:8005/"
export const DETAIL_ISSUE_URL = "http://api.tinylink.cn/problem/detail"
export const LINK_LAB_HOMEPAGE_URL = "http://linklab.tinylink.cn"
export const QUIZE_JUDGE_URL = "http://api.tinylink.cn/problem/quiz/judge"
export const CHOICE_JUDGE_URL = "http://judge.tinylink.cn/quiz/choices/judge"
export const USER_INFO_URL = "http://api.tinylink.cn/user/info"
export const VIEW_DETAIL_URL = "http://api.tinylink.cn/view/active/detail"
export const VIDEO_URL = "http://linklab.tinylink.cn/"
export const QUIZ_CONTENT_URL = "http://judge.tinylink.cn/quiz/content"
export const PROBLEM_STATUS_URL = "http://api.tinylink.cn/problem/status"
export const MULTIPLY_PROBLEM_STATUS_URL = "http://judge.tinylink.cn/problem/status"

