import { DEPLOY_SERVER_DOMAIN } from "./backend-config"
export const AI5DOC= "http://120.55.102.225:12359/weightindex.html"
export const AI4DOC= "http://120.55.102.225:12359/hanxin.html"
export const AI1DOC = "http://linklab.tinylink.cn/static/doc/sidebar1.html"
export const AI2DOC = "http://linklab.tinylink.cn/static/doc/sidebar2.html"
export const AI3DOC = "http://linklab.tinylink.cn/static/doc/sidebar3.html"
export const MODEL_DOWNLOAD_URL = "ws://47.98.249.190:8005/"
export const DETAIL_ISSUE_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/problem/detail`
export const LINK_LAB_HOMEPAGE_URL = `http://linklab.${DEPLOY_SERVER_DOMAIN }`
export const QUIZE_JUDGE_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/problem/quiz/judge`
export const CHOICE_JUDGE_URL = "http://judge.tinylink.cn/quiz/choices/judge"
export const USER_INFO_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/user/info`
export const VIEW_DETAIL_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/view/active/detail`
export const VIDEO_URL = "http://linklab.tinylink.cn/"
export const QUIZ_CONTENT_URL = "http://judge.tinylink.cn/quiz/content"
export const PROBLEM_STATUS_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/problem/status`
export const MULTIPLY_PROBLEM_STATUS_URL = `http://judge.${DEPLOY_SERVER_DOMAIN }/problem/status`
export const FINISH_URL= `http://api.${DEPLOY_SERVER_DOMAIN }/problem/aliyun/report`
export const TEACHER_PPID_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/tview/active/detail`
export const CONFIG_JSON_URL = `http://api.${DEPLOY_SERVER_DOMAIN }/tview/config`